name: lint-wf

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --save-dev HTMLHint stylelint

      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"

      - name: Lint CSS Files
        run: npx stylelint "**/*.css"

      - name: Display package.json content
        run: cat package.json
